### PR TITLE
[WIP] Notion content source implementation

### PR DESCRIPTION
**Pull request by kerwanp**
## 🚧 This is a work in progress

# Supports for [Notion](https://www.notion.so/)

This pull request implements [Notion](https://www.notion.so/) as a content source.

## Related issues
- #174

## Context

Notion is becoming a standard in the industry and almost 100% of our customers use it daily. As a Web Agency we want to provide an easy way for our customers to update the content of their website without relying on us.

We started a while ago the development of [NotionCMS](https://github.com/syneki/notion-cms) a NodeJS library to use Notion as if it was a CMS including a renderer to transform Notion Page Content into HTML.

Unfortunately, there are a lot of problems with the path we decided to took with this tool. This is why we are looking for an alternative and the best solution we found is to implement Notion to Contentlayer.

## Documentation

https://www.contentlayer.dev/docs/sources/notion

## Rendering content

Notion does not use markdown, it looks like but unfortunately for us it is not.
Instead, it returns objects called _blocks_ of different type (paragraph, heading, etc). More information [here](https://developers.notion.com/reference/block).

This is why I created [@notion-render/client](https://github.com/kerwanp/notion-render) a library that transform thoses blocks into HTML. The renderer can be extended to override current blocks and add custom ones to handle Notion Plugins.

## Roadmap
- [x] Handle all simple property types
- [ ] Better implementation of Formula (currently the value type is not inferred)
- [x] Relation property implementation
- [x] Rollup property implementation
- [x] Ability to redefine field keys to keep human readable property names on Notion
- [x] Ability to whitelist properties to generate content without properties containing sensitive values
- [x] Add required option to properties (pages without thoses properties are not generated)
- [x] Add ability to filter and sort databases
- [x] Add pagination iteration system and handle Rate limit
- [x] Computed fields
- [x] Create and use a Notion renderer to transform page content (and RichText properties) into HTML
- [x] Improve performance and codebase architecture
- [ ] Write tests
- WIP

## Example

You can find an example in `examples/node-script-notion`.

> ℹ️ You must have an Internal Integration Token that **has access to the databases you want to fetch**. You can create one [here](https://www.notion.so/my-integrations).

```typescript
import { makeSource, defineDatabase } from 'contentlayer-source-notion';
import * as notion from '@notionhq/client';

const client = new notion.Client({
    auth: '<my-notion-token>'
})

const Post = defineDatabase(() => ({
    name: 'Post',
    databaseId: '<my-database-id>',
    properties: {
        email: { // Remap properties to a custom key
            label: 'Email', // Properties to remap
            isRequired: true, // Content is not generated if the property is required (defaults to false)
        }
    }
}))

export default makeSource({
    client,
    databaseTypes: [Post]
})
```

### CODE REVIEW

**Comment by schickling** [comment]
Very excited to look into this once I'm back from my vacation towards the end of the month. As this is a fairly big change to Contentlayer, it would probably be useful to exchange some DMs via Discord. Feel free to DM me via the Contentlayer Discord channel. :)

**Comment by kerwanp** [comment]
The `contentlayer-source-notion` plugin as been released in Alpha-test ! 🎉 

You can find the documentation on how to configure in the [source repository](https://github.com/kerwanp/contentlayer-source-notion) of this Pull Request.

**Comment by emilienbidet** [comment]
Keep going @kerwanp ! That's a super work

**Comment by airtonix** [comment]
👋🏻  I think I've been trying out the alpha of notion as a content source via contentlayer. 

This is my first time using notion.

One blocker for me at the moment is that i cant seem to be able to add any page i want from notion into contentlayer as it looks like i can only source databases?

**Comment by jmuchovej** [comment]
is it possible to add `meta: never stale` as a label to this?

**Pull request closed without merging**
