### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by timlrx**
# Core dependency and peer dependency updates
Updated Unified, Next.js and Opentelemetry packages. Also list next 14 and esbuild 17-20 as peer dependencies. 

This should solve the top 3/4 most commented issues on contentlayer and allow most folks to continue using it without manual patching:

- Updated unified js and remark/rehype packages (fix https://github.com/contentlayerdev/contentlayer/issues/558)
    - Also added an integration test for the latest version of `remark-gfm` (fails on the previous setup and works with the updated dependencies)
- Support next 14 and resolve manual override (https://github.com/contentlayerdev/contentlayer/issues/575)
- Added esbuild 17-20 as peer dependencies and manually tested that the different resolutions work well, keeping the main resolution for the package as 18 (https://github.com/contentlayerdev/contentlayer/pull/620)
- Updated opentelemetry (As proposed in https://github.com/contentlayerdev/contentlayer/pull/519 updating the packages may fix https://github.com/contentlayerdev/contentlayer/issues/506. Can't replicate the issue but the older package works for me with the recent opentelemetry versions without overrides)
- Memfs is fixed to `v3.6.0`. It's an older version but it comes with less dependencies and peer dependencies than `v4` onwards. Nonetheless, I updated `mkdirp` to use the recursive option which would be compatible with `v4` packages should we decide to upgrade.

The largest part of the core dependency that has yet to be updated are the effect packages, but given that the functions in the legacy package still work well I don't think there's a need to migrate it and that could be a subsequent update.

There's also the stackbit and contentful integration. Didn't bother upgrading those as I am neither a user nor a paid maintainer 😄. All the existing tests pass though so hopefully that should be sufficient.

# Dev depedency updates
- Fix changeset configuration (https://github.com/contentlayerdev/contentlayer/pull/622)
- Updated dev dependencies vite to `^5.0.12` and vitest to `1.2.2`
    - Added a `vitest.config.ts` file for each workspace with test as vitest now requires a `moduleDirectories` to resolve correctly
    - Snapshots are updated and double slash escape removed (see https://github.com/vitest-dev/vitest/pull/3961)
    - The readme in the integration tests workspace mentions a threading issue with the older version of Node 16 and Node 14 with windows. I didn't verify that the newest version of Vitest works with the latest node versions, but I think we can just update it and see if the test fails on any of the CI runs. 

# Misc
- Use `awk` instead of `sed` for next-contentlayer prepack script. For some reason the `sed` script did not work on my Mac

### CODE REVIEW

**Review by Shubhdeep12 — APPROVED** [review]

**Comment by timlrx** [comment]
I published a test version of all the changes under `@contentlayer-temp/*`, `contentlayer-temp` and `next-contentlayer-temp`. 

To try it out, you can swap out `contentlayer` and `next-contentlayer` with the temp packages `v0.4.3`, as well as update the relevant imports. The config file and generated content folder still remains the same. 

From my testing on an updated version of `next-contentlayer-example` using `next@14.1.0`, it appears that all the linked issues are fixed with the updates. The updated packages are compatible with the latest unified js packages e.g.

```js
export default makeSource({
  contentDirPath: "posts",
  documentTypes: [Post],
  mdx: {
    remarkPlugins: [remarkGfm],
  },
});
```

Packaging related changes to get it published are over here: https://github.com/timlrx/contentlayer/pull/2

Hope to get it merged it so that all the updates will still be under contentlayer, but if there are no plans for further updates or if there are governance issues that make continuing under the contentlayer brand difficult, I will consider maintaining it separately with a reduce scope. Thank you for all the previous contributions ❤️  I really think it's the best ORM for markdown files and it would be a shame for it to just fade away!

**Comment by ahmed-adly-khalil** [comment]
it seems like this pr is ready? 🙏

**Comment by timlrx** [comment]
Yup, it's ready and it is not stale

**Review by dima-kov — APPROVED** [review]

**Comment by necmettindev** [comment]
is there an update?

**Comment by DoyinDimeji** [comment]
@necmettindev, guess we're just waiting for it to be merged to base.

**Comment by kais-radwan** [comment]
This has been open for two months now, nobody is maintaining this project anymore right ?? time to just make a fork ???

**Comment by kais-radwan** [comment]
So what @timlrx ... can you take this on your shoulders and make a public fork with the changes you've made ?

**Comment by timlrx** [comment]
Had a chat with Schlickling and he is good with me maintaining a separate hard fork. Will post the new repository link soon.

**Comment by kais-radwan** [comment]
That's some great news. waiting for it

**Comment by timlrx** [comment]
In the meantime, I have published [@contentlayer2](https://www.npmjs.com/settings/contentlayer2/packages), [contentlayer2](https://www.npmjs.com/package/contentlayer2) and [next-contentlayer2](https://www.npmjs.com/package/next-contentlayer2).

Feel free to update the packages and bump the version to `0.4.4`.

**Pull request closed without merging**
