### PR TITLE
feat: preserve vfile data from unified processor

### PR DESCRIPTION
**Pull request by stefanprobst**
`unified` plugins can [store custom information](https://github.com/vfile/vfile#vfiledata) on the resulting `VFile` on the [`data` property](https://github.com/vfile/vfile/blob/main/index.d.ts#L44). this can be used e.g. to pass a table of contents or similar.

this PR preserves the information on `VFile.data`.

note that this is done only for the `remark` pipeline, `mdx-bundler` seems to not expose the `vfile` unfortunately (although i haven't used it personally so i might be missing something)

x-ref: #216

### CODE REVIEW

**Comment by stefanprobst** [comment]
for mdx, we could maybe convert any `vfile.data` to a javascript export via a rehype plugin that runs as the last one in the processing pipeline:

```js
import { valueToEstree } from "estree-util-value-to-estree";

function convertVFileDataToExport() {
  return function transformer(tree, vfile) {
    const node = {
      type: "mdxjsEsm",
      data: {
        estree: {
          type: "Program",
          sourceType: "module",
          body: [
            {
              type: "ExportNamedDeclaration",
              declaration: {
                type: "VariableDeclaration",
                declarations: [
                  {
                    type: "VariableDeclarator",
                    id: {
                      type: "Identifier",
                      name: "data",
                    },
                    init: valueToEstree(vfile.data),
                  },
                ],
                kind: "const",
              },
              specifiers: [],
              source: null,
            },
          ],
        },
      },
    };

    tree.children.push(node);
  };
}
```

**Comment by schickling** [comment]
Thanks a lot for raising this PR @stefanprobst. I'm pretty busy right now but hope to find some time soon to act on this! 🤞

**Comment by wrthwhl** [comment]
Hi @stefanprobst, I am really interested in this but primarily for mdx documents. I saw that the PR you raised seems to implement changes only for markdown. Wouldn't it make sense for mdx, too?
Thanks in advance!

**Comment by stefanprobst** [comment]
hi, unfortunately there is [no way](https://github.com/mdx-js/mdx/discussions/2055) to access `vfile.data` when using `mdx-bundler`. i think for mdx, there are two options:
- allow not using `mdx-bundler` for mdx processing, and instead allow providing a custom `unified` pipeline. this is what i am suggesting in https://github.com/contentlayerdev/contentlayer/issues/247 and i've been using this approach personally.
- while `vfile.data` is the only place for plugins to put additional data when processing markdown, "mdx-aware" plugins can use a different approach and add the data as a named export to the syntax tree. this is what [the comment above](https://github.com/contentlayerdev/contentlayer/pull/236#issuecomment-1140959314) shows and what e.g. is done [here for table of contents](https://github.com/stefanprobst/rehype-extract-toc/blob/main/src/mdx.js), but it's up to individual plugins if they support this. for `contentlayer` users, these named exports would then be available via `useMDXComponent` (but needs #246 to be fixed first)

**Comment by wrthwhl** [comment]
Thanks so much for taking the time to clarify and explain! Will use a custom hook as per [your suggestion here](https://github.com/contentlayerdev/contentlayer/issues/246#issuecomment-1152980335) for now.

**Comment by schickling** [comment]
Thanks a lot again for opening this PR @stefanprobst. I've just given it a more thorough look and while I agree with the problems/use cases it addresses, I think there are some open questions/problems we should address before merging:

## 1. Increased document size

Adding a `data` property to each document comes at the "cost" of increasing the document file sizes for all users (even users who might not need this feature):

CleanShot 2022-07-05 at 11 36 31@2x

A possible solution to this concern could be to introduce a configuration option to let users opt-in to this functionality.

## 2. Divergence of Markdown vs MDX behaviour

To what ever degree possible, I'd like to keep the behaviour of Markdown and MDX processing as similar as possible and avoid "gaps" / asymmetries  in terms functionality, APIs and behaviour. Before merging this PR I'd like to better explore and implement ways to maintain the current level of consistency between the MD and MDX.


---

As an alternative approach I could also imagine introducing a way to let the user expose remark/rehype/MDX processing data via `computedFields`. I'd be curious to hear more thoughts/feedback on this as I think it might be the cleanest/simplest solution to the underlying problems.

**Comment by schickling** [comment]
Still WIP.

**Pull request closed without merging**
